### ISSUE TITLE
Hi10 Pro stylus

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [danielotero/linux-on-hi10#12]
Hi, I have a Chuwi Hi10 Pro runing Manjaro-Arch linux. 
In Current Status, the Active Stylus is listed as working.
I have the touchscreen working with touch gestures but, the stylus (on) is not detected.
Was there a specific driver to install to get the stylus to work?
It is an H2 stylus https://www.gearbest.com/tablet-accessories/pp_435776.html?wid=1433363

**Comment by danielotero** [comment]
For me, it always worked with the touchscreen drivers.

But at the end, it's not really practical, because is not distinguishable
from the fingers.

Let me know if I can help you in any way.

**Comment by sheldonmaschmeyer** [comment]
Ya, the stylus was advertised as having pressure levels but didn't (in Windows). It was the worst stylus I have used between my previous convertible Toshiba R20-JK2 and HP Touchsmart TX2. It is a little more precise, but not great. I will search for a good sale, either a generic capacitive active stylus or get a good portable Wacom pad to use with the tablet or laptop.
