### ISSUE TITLE
efivars/CMOS brick by hibernating and (possibly) how to reset CMOS

### ISSUE THREAD

**Issue by Danct12** [danielotero/linux-on-hi10#15]
I bricked my tablet by sending the tablet to hibernate mode.
When I boot after hibernate, it works fine until you load to Arch, showing some kernel information, and then it loads to blankness, nothing on screen, even the lcd panel shut off, I tried hard power off and turn on with nothing, not even a red led.

I hold the power button for a while trying to reset the CMOS, and then it starts working again.
Does anyone have this problem?

I'm on Arch Linux, kernel 4.18.7-arch1-1-ARCH

**Comment by danielotero** [comment]
That looks like it is trying to resume from the hibernation image. Maybe it
became corrupt or you didn't wait long enough.

Try to remove the hibernation image, or removing the resume option from the
kernel cmdline.

If not, a live USB should allow you to see if there is a hardware/firmware
problem.

**Comment by Danct12** [comment]
Tested again, this seems like a firmware problem, the tablet only gets bricked if you disable the annoying boot menu, otherwise it behave like any other laptops.

**Comment by gsantner** [comment]
Hi, wanted to give some info regarding this: I have disabled the Boot-Switch-Menu via de SwitchNow.exe on a temporary installed windows. I don't get the menu anymore and had nothing done in bios/firmware myself.

**Comment by Danct12** [comment]
I'll be posting a video of the incident soon, hopefully it can describe how you can get it to happen on this tablet.

**Comment by Danct12** [comment]
This issue is now fixed with the current kernel, 4.19.11.
