### ISSUE TITLE
Heads-up about alsa-lib bug currently breaking sound

### ISSUE THREAD

**Issue by Orochimarufan** [danielotero/linux-on-hi10#18]
In case anyone else is still watching this repo and comes across this while digging out their Hi10s like me, the current release of alsa-lib in Arch has a bug affecting a lot of Atom devices including the Hi10pro. It's already been fixed but no release with the fix has come out yet.

PulseAudio will not be able to detect anything unless an asound.state is left from back when it was needed, but that will cause all sound through PA to be broken (aplay works though with the old asound.state). This is because with alsa-lib 1.2, the ucm stuff was moved to a new version and a bug in the parser prevents those new files to be read correctly, preventing PA from settin up the device correctly.

The commit fixing it is alsa-project/alsa-lib@e59034a0bec257cc7422a1e9436d936be8696a6f
I made a PKGBUILD for alsa-lib from git to keep me afloat until the next alsa-lib release: https://github.com/Orochimarufan/custom-pkgbuilds/blob/master/alsa-lib-git/PKGBUILD

For future reference it should also be noted that the "alsaucm" utility is useful for these kinds of devices.

**Comment by Danct12** [comment]
I haven't `pacman -Syu` on my Hi10 Plus for a month now, but thanks for the warning and patch!

**Comment by Orochimarufan** [comment]
The fix is included in alsa-lib 1.2.2 which is already in Arch as of right now.
