### ISSUE TITLE
New kernel

### ISSUE THREAD

**Issue by yiping-huang** [danielotero/linux-on-hi10#2]
Arch Linux Kernel 4.13.3-1 is online, and 4.13.4-1 is testing.
Would you please do some update?

**Comment by danielotero** [comment]
I don't expect to see improvements over minor kernel revisions. But the 4.14 branch is already on it's -rc2, so I will build the kernel and see if there is any noticeable improvements.

I don't have much time to fiddle with the device myself, so any help is appreciated.

**Comment by yiping-huang** [comment]
Mine is Hi10Plus. Indeed not much of improvement.
https://github.com/yiping-huang/archlinux_on_hi10_plus
