### ISSUE TITLE
touchscreen calibration

### ISSUE THREAD

**Issue by crackgm** [danielotero/linux-on-hi10#5]
hello
i've just installed driver from this repo and it works actually, but I cant get it calibrated using xinput_calibrator, anyone made it working well??

**Comment by danielotero** [comment]
Sure! Give me some time to recover and organize the way I did it.

It's somehow hackish, but it mostly work.

On 26 October 2017 18:28:20 CEST, crackgm <notifications@github.com> wrote:
>hello
>i've just installed driver from this repo and it works actually, but I
>cant get it calibrated using xinput_calibrator, anyone made it working
>well??
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/danielotero/linux-on-hi10/issues/5

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by danielotero** [comment]
I don't have time now to detailed the steps that I made to get to this configuration, but the final script that I'm using is this one:
```sh
#!/bin/bash

x_scale=1.0
y_scale=1.025
x_offset=0.0
y_offset=-0.051

xinput set-prop 'Silead GSLx680 Touchscreen' --type=float 'libinput Calibration Matrix' ${x_scale} 0 ${x_offset} 0 ${y_scale} ${y_offset} 0 0 1
xinput --map-to-output "Silead GSLx680 Touchscreen" DSI1
````
Test if it also works for you, or you can tweak the {x,y}_{scale,offset} values and get the feeling of how it affects.

**Comment by Orochimarufan** [comment]
you should be able to sign flip the 5th field in your matrix to flip the y axis. Also you should probably use the calibration matrix instead. I found https://github.com/reinderien/xcal helpful to get initial values for manual tweaking

**Comment by danielotero** [comment]
Thanks @Orochimarufan! I never get the xinput_calibrator working, but that project seems much better!

**Comment by crackgm** [comment]
I tried xcal, did calibration, on test the green lines were at the point I clicked but after applying new settings it didn't work, it was touching left upper corner only... anyone had this trouble?

**Comment by crackgm** [comment]
yay, i did it...manually figured out, changing values from xcal

 xinput set-prop 'silead_ts' --type=float 'libinput Calibration Matrix' 2.16, 0.000000, 0.000, 0.000000, -3.312900, 1.013430, 0.000000, 0.000000, 1.000000

**Comment by danielotero** [comment]
I detailed my new findings with libinput, and works with very little configuration now in sway! Just missing the home button functionality.
