### ISSUE TITLE
Backlight control

### ISSUE THREAD

**Issue by crackgm** [danielotero/linux-on-hi10#6]
Hello
I can't figure out where to paste it

CONFIG_PWM=y
CONFIG_PWM_CRC=y
CONFIG_I2C_DESIGNWARE_PLATFORM=y
CONFIG_I2C_DESIGNWARE_PCI=y
CONFIG_INTEL_SOC_PMIC=y
CONFIG_DRM_I915=m

**Comment by Orochimarufan** [comment]
In the kernel config. Or just use the kernel config in this repo

**Comment by crackgm** [comment]
but how to apply this config??? im a bit newbie

**Comment by Orochimarufan** [comment]
Depends on your distribution

**Comment by crackgm** [comment]
antergos arch linux...cant find anything on web, is it related with  rebuilding kernel??

**Comment by Orochimarufan** [comment]
Yeah. On Arch, you can just run 'makepkg -is' inside the kernel folder of this repo after instaling base-devel. Alternatively grab a prebuilt package from https://github.com/yiping-huang/arch_on_hi10plus . Note that building the kernel on the Hi10 itself is going to take a few hours. It's much faster to build it on a different machine (makepkg -s) then install it on the Hi10 (pacman -U)

**Comment by yiping-huang** [comment]
It's working natively using 4.14.8.
